import Link from "next/link";
import { Meta } from "../../components/PageParts";
import { CTA, Layout } from "../../components/SiteChrome";

const rows = [["01","Conversación","Ordena la entrada de WhatsApp, identifica el contexto y permite revisar la respuesta."],["02","Conocimiento","Utiliza información aprobada por el despacho y separada por comunidad."],["03","Incidencia","Convierte el mensaje que requiere actuación en un caso con prioridad y estado."],["04","Tarea","Asigna trabajo, responsable y fecha sin perder el vínculo con la conversación."],["05","Cronología","Conserva decisiones, actualizaciones y resolución en una historia común."]];

export default function Producto() {
  return <Layout><Meta title="Producto" description="Conoce las piezas que conectan la atención y las operaciones en Afincalia." /><section className="overview-intro page-shell"><span className="eyebrow">Vista general del producto</span><h1>Una capa operativa entre el mensaje y el trabajo terminado.</h1><p>Afincalia no intenta reemplazar la contabilidad del despacho. Se centra en lo que ocurre antes, durante y después de cada consulta: entender, responder, organizar, ejecutar y dejar constancia.</p></section><section className="overview-map page-shell">{rows.map(([n,title,text])=><div className="overview-row" key={n}><span>{n}</span><h2>{title}</h2><p>{text}</p></div>)}</section><section className="features-section page-shell"><div className="section-head"><span className="eyebrow">Explora cada área</span><h2>Más detalle, sin promesas genéricas.</h2></div><div className="feature-grid"><Link className="feature-card" href="/producto/whatsapp"><small>Entrada</small><b>↗</b><h3>Atención por WhatsApp</h3><p>Identidad, comunidad, contexto y revisión.</p></Link><Link className="feature-card" href="/producto/conocimiento"><small>Respuesta</small><b>↗</b><h3>Conocimiento verificado</h3><p>Fuentes controladas por el despacho.</p></Link><Link className="feature-card" href="/producto/incidencias-tareas"><small>Ejecución</small><b>↗</b><h3>Incidencias y tareas</h3><p>Trabajo asignado y actualizado.</p></Link><Link className="feature-card" href="/producto/trazabilidad"><small>Control</small><b>↗</b><h3>Trazabilidad</h3><p>Una cronología común para el equipo.</p></Link></div></section><CTA /></Layout>;
}
