import { Meta } from "../components/PageParts";
import { CTA, Layout } from "../components/SiteChrome";

const steps = [
  ["Llega el mensaje", "La conversación muestra el contacto y la comunidad vinculada cuando constan. El equipo revisa ese contexto antes de actuar.", "/demo/07-administration.jpg", "Vista de comunidades del piloto, con datos de demostración."],
  ["Se recupera la información", "El equipo consulta las fuentes y datos verificados de la comunidad, con su procedencia y fecha de revisión.", "/demo/03-knowledge.jpg", "Base de conocimiento del piloto: comunidad, fuentes y datos verificados."],
  ["Se define el siguiente paso", "El equipo decide si responder, pedir información o registrar una incidencia, según el caso y sus permisos.", "/demo/04-incidents.jpg", "Vista de incidencias del piloto: filtros y estado del trabajo."],
  ["El trabajo conserva su contexto", "Incidencias, tareas, responsables y documentos quedan vinculados al asunto correspondiente.", "/demo/04-incidents.jpg", "Listado de incidencias: filtros y estado de un caso con datos simulados."],
  ["Se consulta cada petición", "Cada petición conserva su origen, la respuesta asociada cuando existe y su estado. Una entrega sin confirmar queda señalada para revisión; no se da por aceptada.", "/demo/05-tasks.jpg", "Vista de tareas: filtros de estado, fecha, responsable y comunidad."],
  ["Una persona verifica lo que lo requiere", "La respuesta de un proveedor puede aportar evidencia; no sustituye la comprobación de una reparación ni autoriza decisiones sensibles.", "/demo/05-tasks.jpg", "Vista de tareas completadas y acceso a su archivo."],
  ["Queda una historia consultable", "El despacho ve actuaciones, revisiones, excepciones y estado del caso sin reconstruirlo a partir de mensajes sueltos.", "/demo/07-administration.jpg", "Administración de comunidades con acceso a su cronología."],
];

export default function ComoFunciona(){return <Layout><Meta title="Cómo funciona" description="Del mensaje al siguiente paso: contexto, información verificada, seguimiento por petición y control del equipo."/><section className="case-hero page-shell"><span className="eyebrow">Cómo funciona</span><h1>Del mensaje al siguiente paso, con contexto y control.</h1><p>Una consulta no siempre requiere una incidencia. AfincalIA organiza la información para responder, pedir el dato que falta o organizar el trabajo del equipo, conservando qué está pendiente y qué debe revisar una persona.</p><p>Las capturas ilustran las vistas indicadas e incluyen datos simulados del piloto. No muestran por sí solas la ejecución de todos los pasos descritos.</p></section><section className="case-timeline page-shell">{steps.map(([title,text,image,caption],index)=><article className="case-step" key={`${index}-${title}`}><span>0{index+1}</span><div><h2>{title}</h2><p>{text}</p></div><div><img src={image} alt={caption}/><p>{caption}</p></div></article>)}</section><CTA title="Recorre un ejemplo, paso a paso." text="La demo pública simula una consulta que necesita revisión humana, una incidencia, su tarea y un cierre. No utiliza datos reales ni realiza envíos."/></Layout>}
