import Link from 'next/link';
import { Layout, EMAIL } from '../components/SiteChrome';
import { Meta } from '../components/PageParts';
import { legalConfig, ready } from '../lib/leads';
export async function getServerSideProps() {
  const { name, retention } = legalConfig();
  return { props: { legal: { name, retention }, enabled: ready() } };
}
export default function Privacy({ legal, enabled }) {
  return <Layout><Meta title="Política de privacidad" description="Información sobre el contacto comercial y las solicitudes de demo y piloto de AfincalIA."/><article className="content-page legal-page page-shell"><h1>Política de privacidad</h1><p>Información de la web comercial. Actualizada el 10 de septiembre de 2026.</p>
    {!enabled && <p className="legal-note">El formulario web de captación aún no está habilitado. La identidad completa del responsable y las condiciones de conservación deben quedar publicadas antes de activarlo.</p>}
    <h2>Responsable del contacto y la gestión comercial</h2><p>{legal.name ? `${legal.name} es el responsable del tratamiento de las consultas dirigidas a AfincalIA y de la gestión de sus solicitudes comerciales.` : 'La identidad del responsable del contacto y la gestión comercial está pendiente de publicación.'} Contacto para privacidad: <a href={`mailto:${EMAIL}`}>{EMAIL}</a>.</p><Link href="/aviso-legal">Consultar identificación del titular</Link>
    <h2>Datos tratados por cuenta de despachos o comunidades</h2><p>Esta política de la web comercial no atribuye al titular de AfincalIA la responsabilidad sobre todos los datos alojados en la aplicación. Las funciones de cada parte se determinan según quién decide las finalidades y los medios de cada tratamiento. Cuando AfincalIA trate datos por cuenta de un despacho o una comunidad, deberá hacerlo conforme a las instrucciones y al contrato de encargo o subencargo que corresponda. Las responsabilidades y condiciones aplicables deben concretarse antes de incorporar datos reales.</p>
    <h2>Solicitudes comerciales</h2><p>Los datos que facilites al solicitar información se utilizan para atender tu petición y comunicarnos contigo sobre la demo o el piloto. No se te suscribe a publicidad por presentar una solicitud. No incluyas información personal de vecinos ni documentación privada.</p>
    {enabled && <><h2>Datos del formulario</h2><p>Nombre, despacho, email, teléfono y número de comunidades si los facilitas, mensaje, interés y página de origen. Guardamos la fecha y versión de la información de privacidad aceptada. El tratamiento se limita a responder a tu solicitud y, cuando corresponda, preparar las medidas precontractuales que solicitas.</p><h2>Proveedores del formulario</h2><p>Vercel aloja la web; Supabase almacena las solicitudes; Resend tramita la notificación por correo a AfincalIA. Las condiciones aplicables a estos servicios, incluidos sus encargos y transferencias internacionales, deben quedar documentadas por el responsable.</p><h2>Conservación</h2><p>{legal.retention}</p><h2>Protección frente a abuso</h2><p>Para limitar envíos repetidos se utiliza temporalmente una huella de la dirección de conexión, calculada con una clave privada que cambia su resultado cada día. No se guarda la dirección IP en la tabla de solicitudes. Los registros técnicos del alojamiento se gestionan por separado.</p></>}
    <h2>Canales de contacto</h2><p>Si eliges WhatsApp o correo, tu petición se tramita mediante el canal elegido y se aplican también las condiciones de su proveedor. El teléfono y el email de contacto figuran en el pie de página.</p>
    <h2>Derechos</h2><p>Puedes solicitar acceso, rectificación, supresión, oposición o limitación y, cuando proceda, portabilidad, escribiendo al contacto indicado. Puedes presentar una reclamación ante la <a href="https://www.aepd.es/">Agencia Española de Protección de Datos</a>.</p>
    <h2>Medición y cookies</h2><p>Consulta la <Link href="/cookies">información sobre cookies y medición</Link>. La demo pública utiliza datos de ejemplo y no incorpora información de tu despacho.</p></article></Layout>;
}
