import { Meta } from "../components/PageParts";
import { CTA, Layout } from "../components/SiteChrome";

const safeguards=[
  ["Separación por despacho y comunidad","La información se organiza dentro del ámbito que le corresponde para evitar cruces de contexto."],
  ["Acceso y actuaciones con permisos","Los accesos y acciones se comprueban según el usuario y su despacho. Editar la base de conocimiento, gestionar actas y detener peticiones son actuaciones reservadas al administrador; un empleado puede actualizar las tareas que tiene asignadas."],
  ["Revisión humana","La conversación muestra cuándo requiere intervención y su motivo. El administrador puede asumir una excepción o mantenerla pendiente. Una respuesta asociada a una petición aporta información; no sustituye la comprobación del resultado ni autoriza decisiones sensibles."],
  ["Seguimiento y verificación","La cronología permite distinguir propuestas, actuaciones, responsables y pendientes. El equipo puede revisar excepciones y detener nuevas actuaciones. Un recordatorio enviado o una respuesta del proveedor no sustituyen la comprobación del resultado antes del cierre."],
];

export default function Seguridad(){return <Layout><Meta title="Privacidad y seguridad" description="Enfoque de privacidad y condiciones para evaluar Afincalia antes de incorporar datos reales."/><section className="content-page page-shell"><div className="section-head"><span className="eyebrow">Privacidad y seguridad</span><h1>Primero se valida el producto. Después se acuerda el tratamiento de datos.</h1><p>La demostración y la primera configuración se realizan sin información real del despacho. La incorporación de datos reales solo debe comenzar cuando estén documentadas las responsabilidades, finalidades, accesos, conservación y proveedores implicados.</p></div><div className="policy-grid">{safeguards.map(([title,text])=><article key={title}><h2>{title}</h2><p>{text}</p></article>)}</div><div className="legal-note"><strong>Un compromiso honesto:</strong> esta página explica el enfoque previsto de Afincalia; no sustituye la revisión jurídica ni afirma un cumplimiento automático. Antes de utilizar información real se concretarán las medidas técnicas y organizativas, los contratos necesarios y las condiciones de cada integración.</div></section><CTA eyebrow="Evaluación responsable" title="Comprueba el producto sin exponer información real."/></Layout>}
